import re

path = '/Users/deniz/Documents/Navikont/navikont/navikont/Theme.swift'
with open(path, 'r') as f:
    content = f.read()

# Add all missed string translations
new_entries = """
        "Ayrıca Bu Tarihte Çözülenler": "Also completed on this date",
        "Test Modu Aktivasyonu": "Test Mode Activation",
        "Lütfen önce ilgili anketi doldurunuz.": "Please fill out the related survey first.",
        "Take the Related Survey": "Take the Related Survey",
        "Çok etkiliyor": "Affects a lot",
        "Hiç etkilemiyor": "Doesn't affect at all",
        "Cevaplarınız güvenle kaydedildi.": "Your answers have been safely recorded.",
        "Everything is Fine": "Everything is Fine",
        "4. Sağlık verilerim ve kişisel bilgilerim güvende mi?": "4. Are my health data and personal information safe?",
        "İyi akşamlar 👋": "Good evening 👋",
        "Güncel sağlık durumunuzun doğruluğu açısından, gün içinde bir kez gönderdiğiniz (tamamladığınız) check-in verilerini tekrar değiştiremezsiniz. Bir sonraki gün yeni verilerinizi girebilirsiniz.": "For the accuracy of your current health status, you cannot change the check-in data you submitted (completed) once during the day. You can enter your new data the next day.",
        "Nefes Verin": "Exhale",
        "Egzersizi başlatmak için hazır olun": "Get ready to start the exercise",
        "Programınız İptal Edildi": "Your Program Has Been Canceled",
        "Ana sayfada (Dashboard) bulunan 'Günün Görevleri' kartlarına tıklayarak size atanan günlük anket, ölçüm veya bilgilendirme modüllerine ulaşabilir ve kolayca tamamlayabilirsiniz.": "You can access and easily complete your daily surveys, measurements, or information modules assigned to you by clicking on the 'Today's Tasks' cards on the Dashboard.",
        "Sıkça Sorulan Sorular (SSS)": "Frequently Asked Questions (FAQ)",
        "Sahip Olunan Hastalıklar": "Existing Conditions",
        "Size daha iyi hizmet verebilmemiz için fiziksel özelliklerinizi güncel tutun.": "Keep your physical attributes up to date so we can serve you better.",
        "Yeni şifreler eşleşmiyor": "New passwords do not match",
        "Sunucudan veri alınamadı": "Could not fetch data from server",
        "Tekrar Dene": "Try Again",
        "Bugün kendinizi nasıl hissediyorsunuz?": "How do you feel today?",
        "Sağlık ve Fiziksel Bilgiler": "Health and Physical Information",
        "Hazır Olun": "Get Ready",
        "Verileriniz KVKK kapsamında korunmaktadır": "Your data is protected under KVKK",
        "Çişim geldi, sayacı başlat": "I need to pee, start the timer",
        "Bilgileriniz başarıyla güncellendi.": "Your information has been successfully updated.",
        "Anket yükleniyor...": "Loading survey...",
        "Anketi Aç": "Open Survey",
        "İyi akşamlar ": "Good evening ",
        "NaviKont Programı": "NaviKont Program",
        "Klinik Uyarı": "Clinical Warning",
        "Kan Grubu": "Blood Type",
        "Bugünkü Görevler": "Today's Tasks",
        "Şifre Değiştir": "Change Password",
        "Ana Sayfa": "Home",
        "Navikont, tedavi sürecinizi kolaylaştıran, günlük sağlık durumunuzu ve görevlerinizi takip edip doktorunuzla senkronize olmanızı sağlayan akıllı bir hasta takip platformudur.": "Navikont is a smart patient tracking platform that simplifies your treatment process, tracks your daily health status and tasks, and synchronizes with your doctor.",
        "Evet, girdiğiniz check-in verileri ve anket sonuçları, sizin tedavinizi yakından takip edebilmesi için anlık olarak sadece yetkili doktorunuzun (veya tedavi ekibinizin) ekranına düşmektedir.": "Yes, the check-in data and survey results you enter are instantly displayed only on the screen of your authorized doctor (or treatment team) so they can closely monitor your treatment.",
        "Contact Information": "Contact Information",
        "Task and exercise reminders": "Task and exercise reminders",
        "Devam Et": "Continue",
        "Artık çişinizi yapabilirsiniz": "You can pee now",
        "Bu modülü başarıyla tamamladınız.": "You have successfully completed this module.",
        "Geliştirici test modunu açmak için şifreyi girin.": "Enter the password to open developer test mode.",
        "Gizlilik Politikası ve KVKK Aydınlatma Metni": "Privacy Policy and KVKK Consent Text",
        "Doğum Tarihi": "Date of Birth",
        "Lütfen günlük takip formunu doldurunuz.": "Please fill out the daily tracking form.",
        "9. Uygulama neden aktif bir internet bağlantısı istiyor?": "9. Why does the app require an active internet connection?",
        "7. Bildirim ayarlarını nasıl değiştirebilirim?": "7. How can I change the notification settings?",
        "Veri Bekleniyor": "Pending Data",
        "Görev Yok": "No Tasks",
        "Program Takvimi": "Program Calendar",
        "Giriş ekranında bulunan 'Şifremi Unuttum' bağlantısına tıklayarak e-posta adresinize bir şifre sıfırlama bağlantısı gönderebilirsiniz. Ayrıca profilinizdeki 'Şifre ve Güvenlik' sekmesinden mevcut şifrenizi dilediğiniz zaman değiştirebilirsiniz.": "You can send a password reset link to your email address by clicking the 'Forgot Password' link on the login screen. You can also change your current password at any time from the 'Password & Security' tab in your profile.",
        "Boy (cm)": "Height (cm)",
        "Geçersiz Video": "Invalid Video",
        "Silent Mode": "Silent Mode",
        "Haftalık raporlar ve makaleler": "Weekly reports and articles",
        "Oturumu Kapat": "Log Out",
        "Check-in formu yükleniyor...": "Loading check-in form...",
        "Şifre değiştir": "Change password",
        "Bu güne atanmış bir görev bulunmuyor.": "There are no tasks assigned for this day.",
        "KVKK metni": "KVKK Consent",
        "Gizlilik Politikası": "Privacy Policy",
        "Size Nasıl Yardımcı Olabiliriz?": "How Can We Help You?",
        "Henüz hiç bildiriminiz yok.": "You have no notifications yet.",
        "Yeni Şifre (Tekrar)": "New Password (Confirm)",
        "Şifremi Unuttum": "Forgot Password",
        "Bilinmeyen bir hata oluştu": "An unknown error occurred",
        "Oturum süresi doldu. Lütfen tekrar giriş yapın.": "Session expired. Please log in again.",
        "Anketi Başlat": "Start Survey",
        "Programınız Donduruldu": "Your Program is Suspended",
        "Şifre en az 6 karakter olmalıdır": "Password must be at least 6 characters",
        "8. Tamamladığım bir anketi sonradan değiştirebilir miyim?": "8. Can I change a completed survey later?",
        "Günlük Check-in": "Daily Check-in",
        "Evet / Hayır": "Yes / No",
        "Şifre ve Güvenlik": "Password & Security",
        "Cevabınızı yazın...": "Type your answer...",
        "Tekrar Başla": "Start Over",
        "Şifreniz güncellendi.": "Your password has been updated.",
        "Check-in Tamamlandı!": "Check-in Completed!",
        "İlgili Anketi Çöz": "Take the Related Survey",
        "Her Şey Yolunda": "Everything is Fine",
        "Yeni Şifre": "New Password",
        "Aktive Et": "Activate",
        "Görevi Tamamla": "Complete Task",
        "Egzersize Başla": "Start Exercise",
        "Değerleriniz normal.": "Your values are normal.",
        "Aydınlık": "Light",
        "Karanlık": "Dark",
        "Otomatik": "Auto",
        "Sistem": "System",
        "Profil": "Profile"
"""

# Append nicely
content = content.replace('"Sistem": "System",', '"Sistem": "System",\n' + new_entries)

with open(path, 'w') as f:
    f.write(content)

